### ISSUE TITLE
Išvalyti warningus

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#190]
Pataisyti testai, pašalinant priežastis dėl kurių juose gaunami klaidų pranešimai

---

Šiuo metu leidžiant testus, gaunu didelį kiekį warningų, reikėtų juos išvalyti, pataisant vietas, dėl kurių warningai atsiranda.

**Comment by adp-atea** [comment]
Only warning cause by our project was due to time zones. Apart from that one type of error there are still many deprecation errors that are left which are caused by many different packages. Mostly errors are repeating and they are: 

- default_app_config needs removal
- packaging.version needs to be used in place for distutils Version classes
- exec_module() needs to be used in place for load_module()
- gettext_lazy() needs to be used in place for ugettext_lazy()

**Comment by sirex** [comment]
In this case, add warnings to `pytest.ini` as documented in
https://docs.pytest.org/en/stable/how-to/capture-warnings.html#controlling-warnings
https://docs.python.org/3/library/warnings.html#warning-filter
